#spring.data.mongodb.host
spring:
  data:
    mongodb:
      host: localhost #172.27.32.162 #
      database: Test
      port: 27017
      authentication-database: admin

server:
  servlet:
    context-path: /water
  port: 8002
